### ISSUE TITLE
UTF8 decode

### ISSUE THREAD

**Issue by L4fv** [project-openubl/searchpe#40]
hola estuve probando el api mediante el manual de docker.
pero la api me devuelve con caracteres extraños para las ñ y tildes
ejemplo:
ruc 10717046850
resultado: YARINGA�O 
Estaré revisando igualmente y les comento en caso tenga un PR

**Comment by carlosthe19916** [comment]
@L4fv Es cierto lo que mencionas. El problema real es que el padrón reducido de la SUNAT parece no tener un `Charset` definido para todo el archivo. En situaciones normales, bastaría con modificar esta linea:

https://github.com/project-openubl/searchpe/blob/master/src/main/java/io/github/project/openubl/searchpe/managers/UpgradeDataManager.java#L119

```java
try (BufferedReader br = new BufferedReader(new FileReader(file))) {
```
Y convertirlo a:

```java
try (BufferedReader br = new BufferedReader(new FileReader(file, StandardCharsets.ISO_8859_1))) {
```

Con eso debería de ser suficiente para leer un archivo con caracteres especiales como la tilde o ñ. Hace tiempo probé hacer el cambio pero arreglaba las tiltes y ñ pero por otro lado malograba otros caracteres especiales como los espacios.

Si tienes alguna idea de cómo solucionar este problema con gusto podemos intentarlo juntos.
